"""Generates a SlidePlan from project_proposal.md using PydanticAI."""

import os
import sys

sys.stdout.reconfigure(encoding="utf-8")

from dotenv import load_dotenv
from pydantic_ai import Agent

from models import SlidePlan

load_dotenv()

MODEL_NAME = os.getenv("REEL_MODEL", "openai:gpt-5.6-luna")

# TODO: write the system prompt. It must tell the model:
#   - it receives a project proposal as plain text input
#   - it must produce a SlidePlan with 4-6 slides (the schema already
#     enforces this, but say it anyway so the model doesn't try for 10
#     and get its output rejected)
#   - each slide needs:
#       - `description`: what's on screen (text + visuals)
#       - `narration`: what's spoken aloud - keep it short, ~15 seconds
#         of speech is roughly 2-3 sentences
#   - the slides should pitch the proposal (problem, what it is, why it
#     fits the course, scope/roadmap, etc.) - the exact breakdown is your
#     call
SYSTEM_PROMPT = """
You will be given the text of a project proposal for a course video reel
about a video game called Capital Syndicate: Financial Reality Engine.

Turn it into a slide plan with exactly 6 slides, covering these beats in
order:

1. The hook: this is a finance-themed open-world game, GTA-style - you
   live inside it and do things you can't do in real life, like trade
   stocks, buy real estate, steal cars, text NPCs to hit on them, commit
   crimes and go to jail, go fishing, visit a church, or gamble at a
   casino with real in-game bets.
2. A highlight of the most visual, fun parts of the game: driving,
   casino mini-games, and the church/chapel landmark.
3. The AI angle: an in-game social media feed is generated by AI and
   actually moves stock prices, and the NPCs you can text with are also
   AI-generated.
4. The goal: build toward $10M net worth through a tiered milestone
   ladder ($50k -> $250k -> $1M -> $5M -> $10M) - that tiered ladder is
   the real win condition. $1B is NOT the win condition; mention it only
   as an aspirational "flex goal" for players who want to keep playing
   past the real win, being clear it is optional bragging rights, not
   the actual target.
5. How it's built: the game itself is developed by a coordinated fleet
   of 10 specialized AI subagents (a producer, game-designer,
   world-builder, gameplay-engineer, art-director, visual-polish,
   technical-artist, audio-director, writer, and qa-tester), each with a
   narrow job, rather than one generalist assistant - this is itself the
   applied-AI/agentic-systems lesson of the project.
6. What's next: making the NPCs feel more alive, finishing the
   smartphone UI, linking social media posts to real in-game stock/
   crypto/real-estate prices, building out the crime/jail system
   (bribe your way out or escape), and improving character and building
   art.

For each slide, write:
- description: what appears on screen - the text and/or visual for that
  slide, in enough detail that someone could build an HTML slide from it.
- narration: what gets spoken aloud for that slide. Keep it to about
  15 seconds of speech, roughly 2-3 short sentences, in an upbeat,
  pitch-like tone.
"""

agent = Agent(MODEL_NAME, output_type=SlidePlan, system_prompt=SYSTEM_PROMPT)


def load_proposal(path: str = "project_proposal.md") -> str:
    with open(path, "r", encoding="utf-8") as f:
        return f.read()


def generate_slide_plan(proposal_text: str) -> SlidePlan:
    result = agent.run_sync(proposal_text)
    return result.output


if __name__ == "__main__":
    proposal = load_proposal()
    plan = generate_slide_plan(proposal)
    print(plan.model_dump_json(indent=2))
