"""Generates a SlidePlan from project_proposal.md using PydanticAI."""

import os
import sys

sys.stdout.reconfigure(encoding="utf-8")

from dotenv import load_dotenv
from pydantic_ai import Agent

from models import SlidePlan

load_dotenv()

MODEL_NAME = os.getenv("REEL_MODEL", "openai:gpt-5.6-luna")

# TODO: write the system prompt. It must tell the model:
#   - it receives a project proposal as plain text input
#   - it must produce a SlidePlan with 4-6 slides (the schema already
#     enforces this, but say it anyway so the model doesn't try for 10
#     and get its output rejected)
#   - each slide needs:
#       - `description`: what's on screen (text + visuals)
#       - `narration`: what's spoken aloud - keep it short, ~15 seconds
#         of speech is roughly 2-3 sentences
#   - the slides should pitch the proposal (problem, what it is, why it
#     fits the course, scope/roadmap, etc.) - the exact breakdown is your
#     call
SYSTEM_PROMPT = """
You will be given the text of a project proposal for a course video reel
about a video game called Capital Syndicate: Financial Reality Engine.

Turn it into a slide plan with exactly 6 slides, covering these beats in
order:

1. The hook: this is a finance-themed open-world game, GTA-style - you
   live inside it and earn your way toward $10M however you want: a day
   job, stock/crypto trading, casino bets, real estate, fishing, or
   crossing to the dark side with call-center scams and black-market
   deals. Every building you visit has its own minigame or puzzle
   instead of a static menu.
2. A highlight of the most visual, fun parts of the game: driving a
   car around the city, casino mini-games, and what happens if you go
   criminal - police chases, jail, and bribing or escaping your way out.
3. The AI angle: an in-game social media feed is generated by AI and
   actually moves stock prices; every NPC is modeled on a real
   historical figure and can be chatted with (and dated) via a live AI
   conversation backend, not scripted dialogue; and a smartphone AI
   assistant answers any question the player has about the game.
4. The goal: build toward $10M net worth through a tiered milestone
   ladder ($50k -> $250k -> $1M -> $5M -> $10M) - that tiered ladder is
   the real win condition, and $10M is the top of it. Do not mention
   $1B or any goal beyond $10M - there isn't one for this slide.
5. How it's built: the game itself is developed by a coordinated fleet
   of 10 specialized AI subagents (a producer, game-designer,
   world-builder, gameplay-engineer, art-director, visual-polish,
   technical-artist, audio-director, writer, and qa-tester), each with a
   narrow job, rather than one generalist assistant - this is itself the
   applied-AI/agentic-systems lesson of the project.
6. What's next (~6 days left): rather than a brand-new prologue world,
   the milestone was re-scoped down to a smaller narrative capstone - a
   win cutscene that plays once the player crosses $10M - plus a
   six-item punch list: tightening the storyline, auditing the stock
   exchange, adding more casino/arcade minigames, straightening the
   existing car-theft/police/jail/bribe flow, confirming the church hub
   is done, and verifying the Lisa romance path. On top of that, a new
   30-day clock: the game already has an "End Day" action that resolves
   the day and advances to the next, counting up forever from Day 1 -
   this caps it into a "Day Left: 30" countdown that drops by one each
   time the player presses End Day. The game only ends once that
   counter reaches zero, not from any single End Day press - be
   precise about this distinction, it's easy to misstate.

For each slide, write:
- description: what appears on screen - the text and/or visual for that
  slide, in enough detail that someone could build an HTML slide from it.
- narration: what gets spoken aloud for that slide. Keep it to about
  15 seconds of speech, roughly 2-3 short sentences, in an upbeat,
  pitch-like tone.
"""

agent = Agent(MODEL_NAME, output_type=SlidePlan, system_prompt=SYSTEM_PROMPT)


def load_proposal(path: str = "project_proposal.md") -> str:
    with open(path, "r", encoding="utf-8") as f:
        return f.read()


def generate_slide_plan(proposal_text: str) -> SlidePlan:
    result = agent.run_sync(proposal_text)
    return result.output


if __name__ == "__main__":
    proposal = load_proposal()
    plan = generate_slide_plan(proposal)
    print(plan.model_dump_json(indent=2))
